profiles:

  - profile-name: ActionProfile
    uuid: *-action-p-10??
    operation-name: string
    label: string
    request: string
    input-value-list:
      - field-name: string
        unit: string
    display-in-new-browser-window: boolean

  - profile-name: IntegerProfile
    uuid: *-integer-p-10??
    integer-name: string
    unit: string
    minimum: integer
    maximum: integer
    integer-value: integer

  - profile-name: StringProfile
    uuid: *-string-p-10??
    string-name: string
    enumeration: array
    pattern: string
    string-value: string

## Add further Profile definitions, if required