profiles:

  - profile-name: 'ActionProfile'
    uuid: '^[a-z]{2,6}-([0-9]+)-([0-9]+)-([0-9]+)-action-p-10[0-9]{2}$'
    capability:
      operation-name: string
      label: string
      input-value-list:
        - field-name: string
          unit: string
      display-in-new-browser-window: boolean
    configuration:
      request: string

  - profile-name: 'IntegerProfile'
    uuid: '^[a-z]{2,6}-([0-9]+)-([0-9]+)-([0-9]+)-integer-p-10[0-9]{2}$'
    capability:
      integer-name: string
      unit: string
      minimum: integer
      maximum: integer
    configuration:
      integer-value: integer

  - profile-name: 'StringProfile'
    uuid: '^[a-z]{2,6}-([0-9]+)-([0-9]+)-([0-9]+)-string-p-10[0-9]{2}$'
    capability:
      string-name: string
      enumeration: array
      pattern: string
    configuration:
      string-value: string

## Add further Profile definitions, if required